// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxytcxhokkcejpawydar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4eXRjeGhva2tjZWpwYXd5ZGFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjM5MzEsImV4cCI6MjA2ODU5OTkzMX0.O9LKfuwIifvkGUsiR2qT14XzF_xvNvVFaQS3Q_LxmLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});